export const educations = [
  {
    id: 1,
    image: "peradaban.png",
    year: "2025 - now",
    company: "Peradaban University",
    title: "Informatic",
    duration: "September 2021 - November 2025",
    short_desc: "lorem dolor ipsum amet",
    tasks: [
      "Software Development Fundamentals",
      "Database Design & Management",
      "State management with Redux Toolkit",
      "Networking & Computer Systems",
      "Software Engineering Practices",
      "Capstone & Research Projects",
    ],
  },
  {
    id: 2,
    image: "bangkit.jpg",
    year: "2025 - now",
    company: "Bangkit Academy",
    title: "Machine Learning",
    duration: "Agustus 2023 - Desember 2023",
    short_desc: "lorem dolor ipsum amet",
    tasks: [
      "Teamwork & Capstone Project Development",
      "Online session and Self learning",
      "Data Preprocessing & Visualization",
      "Supervised & Unsupervised Learning",
      "Deep Learning with TensorFlow",
      "Model Deployment",
    ],
  },
  {
    id: 3,
    image: "hacktiv8.jpg",
    year: "2025 - now",
    company: "Hacktiv8 Indonesia",
    title: "React Js For Frontend Developer",
    duration: "September 2024 - Januari 2025",
    short_desc: "lorem dolor ipsum amet",
    tasks: [
      "Teamwork & Presentation of Projects",
      "Online session and Self learning",
      "State management with Redux Toolkit",
      "Fetch and apply REST API",
      "Rendering Method of Web App",
      "Best practice for creating class & functions in React",
    ],
  },
];
